entityPath: lib/model
dbSchema: public
createController: true
controllerPath: lib/controller
database:
  username: postgres
  password: postgres
  host: localhost
  port: 5432
  databaseName: orm_test
