entityPath: lib/model
dbSchema: public
createEntity: false
createController: true
controllerPath: lib/controller
createTest: true
database:
  username: postgres
  password: postgres
  host: localhost
  port: 5432
  databaseName: orm_test
