entityPath: example/lib/model
dbSchema: public
createEntity: true
createController: true
controllerPath: example/lib/controller
createTest: true
database:
  username: postgres
  password: postgres
  host: localhost
  port: 5432
  databaseName: orm_test
