entityPath: example/lib/model
createController: true
controllerPath: example/lib/controller
dbSchema: public
database:
  username: postgres
  password: postgres
  host: localhost
  port: 5432
  databaseName: orm_test
